### ISSUE TITLE
integration form not showing in Settings>Personal>Connected Accounts

### ISSUE THREAD

**Issue by charlessteiner** [eneiluj/integration_suitecrm#1]
Hey guys. In setting up a Dashboard widget I was expecting to see a form in Settings>Personal>Connected Accounts
There are some references to suiteCRM when I look at HTML source in the browser.

FWiW, I do see the oAuth form in Settings>Administration>Connected Accounts but have not set that up.

Nextcloud 20.0.1
PHP Version: 7.4.12
Centos 8
Apache

browsers:
firefox
brave (with shields down)

**Comment by charlessteiner** [comment]
from check-code

.../apps/integration_suitecrm/lib/Dashboard/SuiteCRMWidget.php
 2 errors
    line   81: OC_Util - Static method of private class must not be called
    line   82: OC_Util - Static method of private class must not be called

**Comment by eneiluj** [comment]
Hi, thanks for the feedback. Configuring a SuiteCRM OAuth app and then Nextcloud admin settings is in fact mandatory to be able to authenticate. There is no other way to let users access the API.

> from check-code

This is unrelated. Half of Nextcloud apps still use this. Anyway it's now fixed so the warning is gone :grin:. Thanks.

v0.0.4 is out. A hint is now displayed in perso settings when admin settings are not set.
