### ISSUE TITLE
Failed: Invalid login/password forever.

### ISSUE THREAD

**Issue by AreYouLoco** [eneiluj/integration_suitecrm#4]
Hi,

I am having problems integrating SuiteCRM with NextCloud. After long time tries and errors I managed to get to the error from the subject.

I managed to login as testuser to SuiteCRM and I followed the wizard until end. So the user and password is correct. I tried to generate my own secret and also used the one from config.php without luck. How do I proceed? Or debug? Which log to check?

**Comment by AreYouLoco** [comment]
Is the secret in config.php BASE64 encoded? Tried encoded and plaintext as a secret without luck. All the time I do get "Failed: Invalid login/password".

**Comment by AreYouLoco** [comment]
https://github.com/eneiluj/integration_suitecrm/issues/2#issuecomment-952185659

**Comment by mr2017x** [comment]
i guess your users are ldap/Active directory synced? this seems to be the issue.

1. test user (local) at suitecrm - works
2. ldap user (working on suitecrm on its own and working on nextcloud on its own) is not working through suitecrm integration in nextcloud
